@server = https://ubiquitous-fortnight-g44j565p464c95ww-8080.app.github.dev
###
GET {{server}}/api/ventas
###
POST {{server}}/api/ventas
Content-Type: application/json

{
    "numero": "100-9009446677",
    "subTotal": 90,
    "impuesto": 10,
    "total":100
}
###
GET {{server}}/api/ventaDetalles
###
POST {{server}}/api/ventaDetalles
Content-Type: application/json

{
    "cantidad": 888,
    "venta": "http://localhost:8080/api/ventas/1",
    "producto": "http://localhost:8080/api/productos/1"
}
###
GET {{server}}/api/productos
###



GET {{server}}/api/musicos
###
POST {{server}}/api/musicos
Content-Type: application/json

{"nombre": "Joaquín"}
###
GET {{server}}/api/bandas
###
GET {{server}}/api/bandas/1
###
GET {{server}}/api/bandas/1/formacion
###
GET {{server}}/api/integrantes
